apiVersion: v1
kind: Pod
metadata:
  name: {{ include "dapr-shared.fullname" . }}-hook
  labels:
    {{- include "dapr-shared.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  # This shows how to use a simple value. This will look for a passed-in value
  # called restartPolicy. If it is not found, it will use the default value.
  # {{default "Never" .restartPolicy}} is a slightly optimized version of the
  # more conventional syntax: {{.restartPolicy | default "Never"}}
  restartPolicy: "Never"
  serviceAccountName: {{ include "dapr-shared.serviceAccountName" . }}
  containers:
  - name: shared-remove-hook
    image: "{{ .Values.shared.initContainer.image.registry }}/{{ .Values.shared.initContainer.image.name }}:{{ .Values.shared.initContainer.image.tag }}"
    args: 
      - remove
      - --config-map={{ .Release.Name }}-cm
