{{- if eq .Values.ambient.strategy "deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dapr-ambient.fullname" . }}
spec:
  replicas: {{ .Values.ambient.replicas | default 1}}
  selector:
    matchLabels:
      {{- include "dapr-ambient.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dapr-ambient.selectorLabels" . | nindent 8 }}
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-proxy 
          image: "{{ .Values.ambient.proxy.image.registry }}/{{ .Values.ambient.proxy.image.name }}:{{ .Values.ambient.proxy.image.tag | default .Chart.AppVersion }}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
{{- end -}}