apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dapr-ambient.fullname" . }}
  labels:
    app: {{ include "dapr-ambient.fullname" . }}
data:
    dapr-api-token: {{ .Values.ambient.daprd.token | b64enc | quote }}
    {{- if .Values.ambient.initContainer.token }}
    app-api-token: {{ .Values.ambient.initContainer.token | b64enc | quote }}
    {{- end }}